version: "3.8"

name: oid4vc_mockup

services:
    app:
        container_name: express-server
        build: .
        ports:
            - "4000:4000"
            - "9229:9229"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
